specs:
  - https://x-series-api.lightspeedhq.com/openapi/61c4ce022f567d0040229dbe
  - https://x-series-api.lightspeedhq.com/openapi/640a3e39612878007ad0f689
  - https://x-series-api.lightspeedhq.com/openapi/61c39e9e886b9701025302a6
  - https://x-series-api.lightspeedhq.com/openapi/64d55e27185303007983b728
  - https://x-series-api.lightspeedhq.com/openapi/61c255dfab9a2b002b9f9d23
  - https://x-series-api.lightspeedhq.com/openapi/61c258b6aad809002170d18e
